blueprint:
  name: View Assist - Thermostat Control
  description: Control thermostat temperature  (View Assist thermostatcontrol v 1.0.1)
  domain: automation
  input:
    increasetemperature:
      name: Increase Temperature
      description: The phrase used to increase the current thermostat temperature set point
      default: "(increase thermostat | raise thermostat | increase temperature | raise temperature) [by] {amount} (degree | degrees | °)"
    decreasetemperature:
      name: Decrease Temperature
      description: The phrase used to decrease the current thermostat temperature set point
      default: "(decrease thermostat | lower thermostat | decrease temperature | lower temperature) [by] {amount} (degree| degrees | °)"
    settemperature:
      name: Set Temperature
      description: The phrase used to set the current thermostat temperature set point
      default: "(set thermostat | change thermostat | set temperature | change temperature) [to] {amount} [degree | degrees | °]"            
    showthermostat:
      name: Show Thermostat
      description: The phrase used to show thermostat
      default: "show thermostat"            
    thermostat:
      name: Thermostat device
      description: The thermostat device to control (example climate.livingroomtstat)
      selector:
        entity:
          filter:
            - domain: climate      
      default: ""      
    view:
      name: View
      description: The View Assist dashboard view to use for thermostat device
      default: "/view-assist/thermostat"
trigger:
  - platform: conversation
    command: !input increasetemperature
    id: increasetemperature
  - platform: conversation
    command: !input decreasetemperature
    id: decreasetemperature
  - platform: conversation
    command: !input settemperature
    id: settemperature
  - platform: conversation
    command: !input showthermostat
    id: showthermostat    
condition: []
action:
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
      amount: "{{ trigger.slots.amount }}"
      thermostat: !input thermostat
      view: !input view
  - action: view_assist.set_state
    target:
      entity_id: "{{ target_satellite_device }}"              
    data:        
      climate: "{{ thermostat }}"      
  - choose:
      - conditions:
          - condition: trigger
            id:
              - increasetemperature
        sequence:
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'cool' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature')+ amount }} 
                target:
                  entity_id: "{{ thermostat }}"
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'heat' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') + amount }} 
                target:
                  entity_id: "{{ thermostat }}"
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'heat_cool' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  target_temp_high: >-
                    {{ state_attr(thermostat,'target_temp_high') + amount }}
                  target_temp_low: >-
                    {{ state_attr(thermostat,'target_temp_low') + amount }}
                target:
                  entity_id: "{{ thermostat }}"
          - set_conversation_response: Thermostat temperature raised {{ amount }} degree
          - if:
              - condition: template
                value_template: "{{ target_satellite_device_type != 'audio_only' }}"
            then:
              - action: view_assist.navigate
                data:
                  device: "{{ target_satellite_device }}"
                  path: "{{ view }}"             
      - conditions:
          - condition: trigger
            id:
              - decreasetemperature
        sequence:
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'cool' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') - amount }} 
                target:
                  entity_id: "{{ thermostat }}"
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'heat' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: >-
                    {{ state_attr(thermostat,'temperature') - amount }} 
                target:
                  entity_id: "{{ thermostat }}"
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'heat_cool' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  target_temp_high: >-
                    {{ state_attr(thermostat,'target_temp_high') - amount }}
                  target_temp_low: >-
                    {{ state_attr(thermostat,'target_temp_low') - amount }}
                target:
                  entity_id: "{{ thermostat }}"
          - set_conversation_response: Thermostat temperature lowered {{ amount }} degree
          - if:
              - condition: template
                value_template: "{{ target_satellite_device_type != 'audio_only' }}"
            then:
              - action: view_assist.navigate
                data:
                  device: "{{ target_satellite_device }}"
                  path: "{{ view }}"             
      - conditions:
          - condition: trigger
            id:
              - settemperature
        sequence:
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'cool' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: "{{ amount }}"
                target:
                  entity_id: "{{ thermostat }}"
          - if:
            - condition: template
              value_template: >-
                {% if states(thermostat) == 'heat' %}
                true
                {% endif %}              
            then:
              - action: climate.set_temperature
                data:
                  temperature: "{{ amount }}"
                target:
                  entity_id: "{{ thermostat }}"
          - set_conversation_response: Thermostat temperature set to {{ amount }} degrees
          - if:
              - condition: template
                value_template: "{{ target_satellite_device_type != 'audio_only' }}"
            then:
              - action: view_assist.navigate
                data:
                  device: "{{ target_satellite_device }}"
                  path: "{{ view }}"             
      - conditions:
          - condition: trigger
            id:
              - showthermostat
        sequence:
          - if:
              - condition: template
                value_template: "{{ target_satellite_device_type != 'audio_only' }}"
            then:
              - set_conversation_response: Showing thermostat
              - action: view_assist.navigate
                data:
                  device: "{{ target_satellite_device }}"
                  path: "{{ view }}"               
            else:
              - set_conversation_response: Sorry.  This device cannot display the thermostat                
    default: []
mode: single