# View Assist - Thank you (v 1.0.0)
# Written by - Dinki
alias: VIEW ASSIST - Thank you
description: ""
trigger:
  - platform: conversation
    command:
      - (Thank you|Thanks) [so much]
      - (You are great|You're Great)
condition: []
action:
  - set_conversation_response: |-
      {{ [
        "Glad I could help",
        "My pleasure",
        "Happy to assist",
        "It was nothing",
        "Anytime",
        "You're too kind",
        "Don't mention it",
        "It's the least I could do"
      ] | random }}
mode: single
