# View Assist - View Assist Search Wikipedia (v 1.0.0)
# Special thanks to Scratt for his work on this blueprint
blueprint:
  name: View Assist - Search Wikipedia
  description: Search for a search term using Wikipedia (View Assist wikisearch v 1.0.0)
  domain: automation
  input:
    command:
      name: Command
      description: The phrase you want to use to trigger searching Wikipedia
      default: "(Tell me about [the] {searchterm}| search [for] {searchterm})"
    dashboard_infopic:
      name: Dashboard Infopic
      description: The View Assist dashboard view to use for info and pic
      default: "/view-assist/infopic"
    dashboard_info:
      name: Dashboard Info Only
      description: The View Assist dashboard view to use for info only
      default: "/view-assist/info"  
alias: View Assist - Search Wikipedia
description: Search for a search term using Wikipedia (View Assist wikisearch v 1.0.0)
trigger:
  - platform: conversation
    command:
      - !input command
condition: []
action:
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
  - action: pyscript.search_wikipedia
    response_variable: wiki_response
    data:
      searchterm: "{{ trigger.slots.searchterm }}"
  - action: view_assist.set_state
    target:
      entity_id: "{{ target_satellite_device }}"              
    data:       
      title: Wikipedia Search
      message_font_size: 3vw
  - choose:
    - conditions:
      - condition: template
        value_template: >-
          {% if wiki_response['thumbnail'] != None %}true{%
          else %}false{% endif %}
      sequence:
        - action: view_assist.set_state
          target:
            entity_id: "{{ target_satellite_device }}"              
          data:       
            message: "{{ wiki_response['extract'] }}"
            image: "{{ wiki_response['thumbnail'] }}"
        - set_conversation_response: "{{ wiki_response['extract'] }}"
        - action: view_assist.navigate
          data:
            device: "{{ target_satellite_device }}"
            path: !input dashboard_infopic
    - conditions:
      - condition: template
        value_template: >-
          {% if wiki_response['type'] != 'disambiguation' %}true{%
          else %}false{% endif %}      
      sequence:
        - action: view_assist.set_state
          target:
            entity_id: "{{ target_satellite_device }}"              
          data:       
            message: "{{ wiki_response['extract'] }}"
        - set_conversation_response: "{{ wiki_response['extract'] }}"
        - if:
          - condition: template
            value_template: >-
              {{ ('view' in state_attr(repeat.item, 'type')) }}
          then:        
            - action: view_assist.navigate
              data:
                device: "{{ target_satellite_device }}"
                path: !input dashboard_info
    default:
      - set_conversation_response: Sorry, I couldn't find anything on Wikipedia for that
mode: single