blueprint:
  name: Play Sound on Media Player
  description: Play a sound file on a specific media player entity
  domain: script
fields:
  media_player:
    description: The media player entity to play the sound on
    example: media_player.living_room_speaker
    required: true
    selector:
      entity:
        domain: media_player
  sound_file:
    description: The URL or file path of the sound to play
    example: /local/sounds/alert.mp3
    required: true
    selector:
      text:
        multiline: false
sequence:
  - data:
      entity_id: "{{ media_player }}"
      media_content_id: "{{ sound_file }}"
      media_content_type: music
    action: media_player.play_media
  - action: media_player.clear_playlist
    target:
      entity_id: "{{ media_player }}"
    enabled: true
mode: single
icon: mdi:file-music-outline  
