# View Assist - Spell a Word (v 1.0.1)
# Written by - Dinki
blueprint:
  name: View Assist - Spell a Word
  description: Ask Assist to spell a word and it spells the word letter-by-letter and displays the word on screen where applicable (View Assist spellaword v 1.0.1)
  domain: automation
  input:
    language:
      name: Language
      description: The desired spoken language
      default: en
      selector:
        language:
          languages: [en, it, de, fr]
    command_prompt:
      name: Command Text
      description: The phrase you want to use to trigger the automation
      default: "[please] [how do you| can you] spell {word}"
    view:
      name: Dashboard view
      description: The View Assist dashboard view to use for displaying text (example /dashboard-viewassist/info)
      default: "/view-assist/info"
alias: View Assist - Spell a Word
description: "Ask Assist to spell a word and it spells the word letter-by-letter and displays the word on screen where applicable"
trigger:
  - platform: conversation
    command:
      - !input command_prompt
condition: []
action:
  - variables:
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
      language: !input language
      command_prompt: !input command_prompt
      view: !input view
      spaced_text: >-
        {% set spaced_text = '...'.join(trigger.slots.word) %}
        {{ spaced_text }}
      translations:
        en:
          responses:
            spell: "{word} is spelled ... {spaced_text}"
        it:
          responses:
            spell: "{word} si scrive ... {spaced_text}"
        de:
          responses:
            spell: "{word} wird buchstabiert ... {spaced_text}"
        fr:
          responses:
            spell: "{word} s’écrit ... {spaced_text}"

      conversation_response: >-
        {{ translations[language]['responses']['spell'].replace("{word}", trigger.slots.word).replace("{spaced_text}", spaced_text) }}
  - set_conversation_response: "{{ conversation_response }}"
  - action: view_assist.set_state
    target:
      entity_id: "{{ target_satellite_device }}"
    data:
      last_said: "{{ conversation_response }}"
  - if:
      - condition: template
        value_template: >-
          {% if target_satellite_device_type != 'audio_only' %}true{% else
          %}false{% endif %}
    then:
      - action: view_assist.set_state
        target:
          entity_id: "{{ target_satellite_device }}"
        data:
          message: <center>{{ trigger.slots.word |upper }}</center>
          message_font_size: 6vw
      - action: view_assist.navigate
        data:
          device: "{{ target_satellite_device }}"
          path: "{{ view }}"
mode: single

