# Version 0.0.6
# 
# What's changed
# ==============
#   
#   * Support up to four players.  Use dictionary to hold players.  Can have names
#   * Support multiple playlists (any MA playlist including local)
#   * Fix ask_question time out by using continue on error.  AI reports condition 4 to tell user they took too long
#   * Create dictionary for player scores
#   * Change ending to determine winner with multiple players
#
# What it does
#
#   * Loops through rounds set by variable number_of_rounds
#   * Plays random song using MA Spotify playlist for ten seconds
#   * Prompts for guess of song and artist
#   * Evaluates guess using OpenAI with ai_score return variable.  Returns 0 if wrong, 1 is title or artist is correct, 2 if both are correct
#   * Calculates score by multiplying ai_score * 100 and gives bonus 100 point if both title and artist are correct
#   * Provides voice response of the guess results and score
#   * Provides final score
#    * Set variables using standard VA methods for satellite devices (musicplayer, assist_satellite, display, etc)
#
# Things to do:
#
#   * Support additional AI agents
#   * Turn into blueprint for variables:
#       * Number of rounds
#       * Playlist dictionary
#       * Amount of time to play song
#    * Create view for visual
#    * Add ability to stop game at any point by voice and touch
#    * Switch to 'game' mode to prevent revealing answer if auto music mode enabled
#    * Switch to flashing bar to not obscure play screen when that gets implemented
#    * Change score report per round from cumulative to round based to make it harder to know who is leading
#
# Issues:
# 
#   * AI has issues with numbers in titles.  May be using words and not matching numerals.  Also issues with additional data 
#     in title and artist and not cosidering it to be a match

alias: View Assist - Song Quiz AI
description: ""
triggers:
  - trigger: conversation
    command:
      - play song quiz
conditions: []
actions:
  - variables:
      target_ha_satellite_device: "{{ trigger.satellite_id }}"
      target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
      target_musicplayer_device: "{{ state_attr(target_satellite_device, 'musicplayer_device')}}"
      target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
  - variables:
      number_of_players: 2
      number_of_rounds: 4
      player_scores: "{{ {'1': 0, '2': 0, '3': 0, '4': 0} }}"
      playlist_kpop: spotify:playlist:2EoheVFjqIxgJMb8VnDRtZ
      playlist_80s: spotify:playlist:19PgP2QSGPcm6Ve8VhbtpG
      playlist_90s: spotify:playlist:37i9dQZF1DXbTxeAdrVG2l
      playlist_2000s: spotify:playlist:37i9dQZF1DX4o1oenSJRJd
      playlist_2010s: spotify:playlist:37i9dQZF1DX4UtSsGT1Sbe
      playlist_today: spotify:playlist:37i9dQZEVXbMDoHDwVN2tF
  - action: assist_satellite.announce
    target:
      entity_id: "{{ target_ha_satellite_device }}"
    data:
      message: Welcome to Song Quiz, the song guessing game.  Let's get started!
      preannounce: false
  - repeat:
      count: "{{ number_of_rounds }}"
      sequence:
        - variables:
            ai_answer: "0"
          enabled: false
        - action: assist_satellite.announce
          target:
            entity_id: "{{ target_ha_satellite_device }}"
          data:
            message: |-
              {% if repeat.index < number_of_rounds %}
                Round {{ repeat.index }}
              {% else %}
                This is the last round
              {% endif %}
            preannounce: false
        - repeat:
            count: "{{ number_of_players }}"
            sequence:
              - variables:
                  ai_answer: "0"
                  song_guess: ""
                  current_player: "{{ repeat.index }}"
              - action: assist_satellite.announce
                target:
                  entity_id: "{{ target_ha_satellite_device }}"
                data:
                  message: Player {{ current_player }} here is your song
                  preannounce: false
              - action: media_player.shuffle_set
                metadata: {}
                data:
                  shuffle: true
                target:
                  entity_id: "{{ target_musicplayer_device }}"
              - action: music_assistant.play_media
                metadata: {}
                target:
                  entity_id: "{{ target_musicplayer_device }}"
                data:
                  media_type: playlist
                  media_id: "{{ playlist_80s }}"
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 10
                  milliseconds: 0
              - action: media_player.media_pause
                metadata: {}
                target:
                  entity_id: "{{ target_musicplayer_device }}"
                data: {}
              - action: assist_satellite.ask_question
                metadata: {}
                data:
                  question: What song just played?
                  preannounce: false
                  entity_id: "{{ target_ha_satellite_device }}"
                response_variable: song_guess
                continue_on_error: true
              - variables:
                  ai_prompt: >-
                    You are judge of a music game.  I will provide you with the
                    correct song title and song artist as well as  the user's
                    guess.  I want you to tell me if they got the answer
                    correct.  The user's guess and the correct  title and/or
                    artist should be a match but extra data in the title like
                    the year, things in parenthesis, foreign characters and
                    other none essential information should not be counted
                    against the user's guess.  User input is from STT so some
                    words may be misspelled.  Simple words like 'the', 'and' and
                    others can be omitted unless they are deemed necessary to
                    the overall meaning.  Use your best judgement.  Be fair but
                    kind. The user input may provide the song title, the song
                    title and artist or just artist

                    I want you to respond with a zero if nothing is correct,
                    answer with one if the song title is correct, answer with
                    two if the song artist is correct, and answer with three if
                    song title and song artist is correct. If user guess is
                    empty then return four

                    Correct song title: {{ state_attr(target_musicplayer_device,
                    'media_title') }} 


                    Correct song artist: {{
                    state_attr(target_musicplayer_device, 'media_artist') }} 


                    User guess: {{ song_guess.sentence }}


                    Only respond with a number.  Nothing else.  It should be the
                    number and not the word representing the number.  So 0, 1,
                    2, 3, or 4 only
              - action: openai_conversation.generate_content
                data:
                  config_entry: 01J3BJ7KG89K0C82N45MQQ2F0G
                  prompt: "{{ ai_prompt }}"
                response_variable: ai_answer
              - variables:
                  ai_score: "{{ ai_answer.text | trim }}"
                  title: "{{ state_attr(target_musicplayer_device, 'media_title') }}"
                  artist: "{{ state_attr(target_musicplayer_device, 'media_artist') }}"
                  song_info: The song was {{ title }} by {{ artist }}
                  round_score: |
                    {% set score = ai_score | int %}
                    {% if score == 3 %}
                      300
                    {% elif score in [1, 2] %}
                      100
                    {% elif score in [0, 4] %}
                      0
                    {% else %}
                      0
                    {% endif %}                    
                  current_player_score: "{{ player_scores[current_player | string] }}"
                  tts_message: |-
                    {% set response_map = {
                      '0': "Incorrect! " ~ song_info,
                      '1': "You got the song title right. " ~ song_info,
                      '2': "You got the artist right. " ~ song_info,
                      '3': "Wow, you got both the song title and artist correct.",
                      '4': "You took too long. " ~ song_info,
                    } %}
                    {{ response_map.get(ai_score  | string, song_info) }}
              - variables:
                  player_scores: >-
                    {{ dict(player_scores, **{current_player | string:
                    current_player_score + round_score}) }}                  
                enabled: true
              - action: assist_satellite.announce
                target:
                  entity_id: "{{ target_ha_satellite_device }}"
                data:
                  message: "{{ tts_message }}"
                  preannounce: false
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ repeat.index < number_of_rounds }}"
                    sequence:
                      - action: assist_satellite.announce
                        target:
                          entity_id: "{{ target_ha_satellite_device }}"
                        data:
                          message: >-
                            Your score is {{ player_scores[current_player |
                            string] }}
                          preannounce: false
  - action: assist_satellite.announce
    target:
      entity_id: "{{ target_ha_satellite_device }}"
    data:
      preannounce: false
      message: >-
        {% set active = player_scores
          | dictsort(by='key')
          | list
        %}

        {% set active = active[:number_of_players] %} {% set ranked = active |
        sort(attribute=1) %}

        {% if number_of_players == 2 %}
          {% set second = ranked[0] %}
          {% set first = ranked[1] %}
          Player {{ first[0] }} is the winner with a score of {{ first[1] }}.
          Player {{ second[0] }} came in second with a score of {{ second[1] }}.
        {% else %}
          {% for entry in ranked %}
            {% set place = loop.index %}
            {% if loop.last %}
              And our champion is Player {{ entry[0] }} with a score of {{ entry[1] }}!
            {% elif place == ranked | length - 1 %}
              In second place is Player {{ entry[0] }} with a score of {{ entry[1] }}.
            {% elif place == ranked | length - 2 %}
              Coming in third is Player {{ entry[0] }} with a score of {{ entry[1] }}.
            {% else %}
              Player {{ entry[0] }} finished in place {{ place }} with a score of {{ entry[1] }}.
            {% endif %}
          {% endfor %}
        {% endif %}
  - action: assist_satellite.announce
    target:
      entity_id: "{{ target_ha_satellite_device }}"
    data:
      message: That's the end of the game.  Hope you had fun!
      preannounce: false
mode: single
