# View Assist template sensor configuration
#
# You must set the following variables:
#  * name: Device name (eg ViewAssist-livingroom)
#  * type:  Used to determine a/v capabilities ("view_audio", "view_only", "audio_only". Default "view_audio")
#  * mic_device:  Used to assign microphone to View Assist device
#  * mediaplayer_device: Used to assign the media player used for View Assist audio playback
#  * timer_device: Used to assign the timer helper device used for screen time outs
#  * display_device: Used to determine the correct Browser Mod instance to use for display
#  * browser_id: Used to assign the browser being used by Browsermod.  This will match the name you give the device in your Browsermod configuration
#  * view_timeout: Amount of time (seconds) before switching views as controlled by mode (Default 20 seconds)
# All other lines should be copied as is without change
#
# Multiple sensors can be created by copy pasting the definition from the "- name" line until the end of
# The "do not disturb line" to the end of the template block and modifying with the next sensor details
# You must create a timer helper device per device
# You must create a sesnor helper group (eg group.viewassist_satellites) and include all View Assist satellites in the group
#
# Example data included below.  This must be changed with your sensor values

template:
  - sensor:
    - name: ViewAssist-livingroom
      state: ""
      attributes:
        type: view_audio
        mic_device: "sensor.streamassist-livingroom_stt"
        mediaplayer_device: "media_player.browsermod-livingroom"
        display_device: "sensor.browsermod-livingroom_browser_path"
        browser_id: "ViewAssist-livingroom"
        timer_device: "timer.viewassist-livingroom"
        view_timeout: "20"
        mode: "normal"
        title: ""
        message: ""
        message_font_size: "3vw"
        image: ""
        timer: ""
        alarm: "idle"
        cycle_view: ""
        do_not_disturb: false
        
