blueprint:
  name: View Assist - Get Sports Scores
  description: Get sports scores for your favorite teams (View Assist getsportsscores
    v 1.1.0)
  domain: automation
  input:
    team_tracker:
      name: Team Tracker Sensor
      description: The Team Tracker sesnor entity that holds data (example sensor.team_tracker)
      default: sensor.team_tracker
      selector:
        entity:
          filter:
          - domain:
            - teamtracker
          multiple: false
    college_teams:
      name: College Teams
      description: College Teams can be added but it is complicated.  You will need
        to know a few specifics for defining.  See Team Tracker docs here.
      default:
        college_teams:
          lsu football:
            team_id: LSU
            conference_id: '8'
            league_path: college-football
            sport_path: football
      selector:
        object: {}
    view:
      name: Dashboard Sports view
      description: The View Assist dashboard view to use for sports scores (example
        /view-assist/sports)
      default: /view-assist/sports
  source_url: https://raw.githubusercontent.com/dinki/View-Assist/viewassist-getsportsscores/View%20Assist%20custom%20sentences/Get%20Sports%20Scores/blueprint-getsportsscores.yaml
trigger:
- platform: conversation
  command:
  - how did [the] {team} do
  - (what is | what's) the score of the {team} (game | match)
  - how (is | are) [the] {team} doing
  - how (is | are) [the] {team} (game | match) [going]
condition: []
action:
- variables:
    target_satellite_device: "{{ view_assist_entity(trigger.device_id) }}"
    target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device')}}"
    target_satellite_device_type: "{{ state_attr(target_satellite_device, 'type')}}"
    view: !input view
    team_tracker: !input team_tracker
    college_teams: !input college_teams
    mlb_teams:
      d backs: ari
      braves: atl
      orioles: bal
      red sox: bos
      cubs: chc
      white sox: chw
      reds: cin
      guardians: cle
      rockies: col
      tigers: det
      astros: hou
      royals: kc
      angels: laa
      dodgers: lad
      marlins: mia
      brewers: mil
      twins: min
      mets: nym
      yankees: nyy
      athletics: oak
      phillies: phi
      pirates: pit
      padres: sd
      san francisco giants: sf
      mariners: sea
      saint louis cardinals: stl
      rays: tb
      texas rangers: tex
      blue jays: tor
      nationals: wsh
    nfl_teams:
      falcons: atl
      ravens: bal
      bills: buf
      carolina panthers: car
      bears: chi
      bengals: cin
      browns: cle
      cowboys: dal
      broncos: den
      lions: det
      packers: gb
      texans: hou
      colts: ind
      jaguars: jax
      chiefs: kc
      raiders: lv
      chargers: lac
      rams: lar
      dolphins: mia
      vikings: min
      patriots: ne
      saints: 'no'
      new york jets: nyj
      eagles: phi
      steelers: pit
      49ers: sf
      seahawks: sea
      buccaneers: tb
      titans: ten
      commanders: was
      new york giants: nyg
      arizona cardinals: arz
    nba_teams:
      hawks: atl
      celtics: bos
      nets: bkn
      hornets: cha
      bulls: chi
      cavaliers: cle
      mavericks: dal
      nuggets: den
      pistons: det
      warriors: gs
      rockets: hou
      pacers: ind
      clippers: lac
      lakers: lal
      grizzlies: mem
      heat: mia
      bucks: mil
      timberwolves: min
      pelicans: 'no'
      knicks: ny
      thunder: okc
      magic: orl
      76ers: phi
      suns: phx
      trail blazers: por
      sacramento kings: sac
      spurs: sa
      raptors: tor
      jazz: uta
      wizards: was
    wnba_teams:
      dream: atl
      sky: chi
      sun: conn
      wings: dal
      fever: ind
      aces: lv
      sparks: la
      lynx: min
      liberty: ny
      mystics: was
      mercury: phx
      storm: sea
    mls_teams:
      atlanta united: atl
      austin fc: atx
      charlotte fc: clt
      fire: chi
      fc cincinnati: cin
      rapids: col
      crew: cbus
      dc united: dc
      fc dallas: dal
      dynamo: hou
      sporting: kc
      galaxy: lag
      los angeles fc: lafc
      inter: mia
      minnesota united: min
      cf montreal: mtl
      sc: nsh
      revolution: ner
      new york city fc: nyc
      red bulls: nyrb
      city: stl
      union: phi
      timbers: por
      real: rsl
      earthquakes: sj
      sounders: sea
      toronto fc: tor
      whitecaps: van
    nhl_teams:
      bruins: bos
      sabres: buf
      flames: cal
      hurricanes: car
      blackhawks: chi
      avalanche: col
      blue jackets: cbj
      stars: dal
      red wings: det
      oilers: edm
      florida panthers: fla
      los angeles kings: la
      wild: min
      canadiens: mtl
      predators: nsh
      devils: njd
      islanders: nyi
      new york rangers: nyr
      senators: ott
      flyers: phi
      penguins: pit
      sharks: sj
      lightning: tb
      maple leafs: tor
      canucks: van
      capitals: was
      winnipeg jets: wpg
      kraken: sea
      blues: stl
      golden knights: vgk
      ducks: ana
      clo: chi
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in mlb_teams }}'
  then:
  - variables:
      query_team: '{{ mlb_teams[(trigger.slots.team)|lower] }}'
      sport_path: baseball
      league_path: mlb
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
      is_singular: false
    enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in nfl_teams }}'
  then:
  - variables:
      query_team: '{{ nfl_teams[(trigger.slots.team)|lower] }}'
      sport_path: football
      league_path: nfl
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
      is_singular: false
    enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in nba_teams }}'
  then:
  - variables:
      query_team: '{{ nba_teams[(trigger.slots.team)|lower] }}'
      sport_path: basketball
      league_path: nba
      is_singular: false
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
    enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in wnba_teams }}'
  then:
  - variables:
      query_team: '{{ wnba_teams[(trigger.slots.team)|lower] }}'
      sport_path: basketball
      league_path: wnba
      is_singular: false
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
    enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in mls_teams }}'
  then:
  - variables:
      query_team: '{{ mls_teams[(trigger.slots.team)|lower] }}'
      sport_path: soccer
      league_path: mls
      is_singular: false
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
    enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in nhl_teams }}'
  then:
  - variables:
      query_team: '{{ nhl_teams[(trigger.slots.team)|lower] }}'
      sport_path: hockey
      league_path: nhl
      is_singular: false
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data:
      sport_path: '{{ sport_path }}'
      team_id: '{{ query_team |lower}}'
      league_path: '{{ league_path }}'
    enabled: true
  enabled: true
- if:
  - condition: template
    value_template: '{{ (trigger.slots.team)|lower in college_teams }}'
  then:
  - variables:
      query_team: '{{ college_teams[(trigger.slots.team)|lower][''team_id''] }}'
      sport_path: '{{ college_teams[(trigger.slots.team)|lower][''sport_path''] }}'
      league_path: '{{ college_teams[(trigger.slots.team)|lower][''league_path'']
        }}'
      conference_id: '{{ college_teams[(trigger.slots.team)|lower][''conference_id'']
        }}'
      is_singular: true
  - service: teamtracker.call_api
    target:
      entity_id: '{{ team_tracker }}'
    data: "{{\n  {\n    \"sport_path\": sport_path,\n    \"team_id\": query_team |lower,\n
      \   \"league_path\": league_path,\n     \"conference_id\": conference_id | string\n
      \ }\n}}\n"
    enabled: true
- set_conversation_response: "{% if is_state(team_tracker, 'POST')%}\n  {% if is_singular
    is false %}\n    The {{state_attr(team_tracker,'team_name')}} played the {{state_attr(team_tracker,'opponent_name')}}
    and\n  {% else %}\n    {{state_attr(team_tracker,'team_name')}} played {{state_attr(team_tracker,'opponent_name')}}
    and\n  {% endif %}  \n    {% if is_state_attr(team_tracker,'team_winner', false)
    %}\n      lost\n    {% else %}\n      won\n    {% endif %} \n  {{state_attr(team_tracker,'team_score')}}
    - {{state_attr(team_tracker,'opponent_score')}}  \n{% elif is_state(team_tracker,
    'PRE') %} \n  {% if is_singular is false %}\n    The {{state_attr(team_tracker,'team_name')}}
    play the {{state_attr(team_tracker,'opponent_name')}} {{state_attr(team_tracker,'kickoff_in')}}\n
    \ {% else %}\n    {{state_attr(team_tracker,'team_name')}} plays {{state_attr(team_tracker,'opponent_name')}}
    {{state_attr(team_tracker,'kickoff_in')}}\n  {% endif %}\n{% elif is_state(team_tracker,
    'IN') %} \n  {% if is_singular is false %}\n    The {{state_attr(team_tracker,'team_name')}}
    are currently playing the {{state_attr(team_tracker,'opponent_name')}}. \n  {%
    else %}\n    {{state_attr(team_tracker,'team_name')}} is currently playing {{state_attr(team_tracker,'opponent_name')}}.
    \n  {% endif %}\n  The score is {{state_attr(team_tracker,'team_name')}} {{state_attr(team_tracker,'team_score')}},
    {{state_attr(team_tracker,'opponent_name')}}  {{state_attr(team_tracker,'opponent_score')}}
    \n{% elif is_state(team_tracker, 'NOT_FOUND') %} \n  The {{ trigger.slots.team
    }} have no games on today's schedule\n{% else %} \n  Sorry.  I could not find
    any recent or upcoming games for the {{ trigger.slots.team }}\n{% endif %}"
- if:
  - condition: template
    value_template: '{{ target_satellite_device_type != ''audio_only'' }}'
  then:
  - action: view_assist.set_state
    target:
      entity_id: '{{ target_satellite_device }}'
    data:
      title: ''
      team_tracker: '{{ team_tracker }}'
  - data:
      device: "{{ target_satellite_device }}"
      path: '{{ view }}'
    action: view_assist.navigate      
mode: single
